#!/usr/bin/env python3
import sys
import os
# パッケージのパスを追加
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from gr00t_controller.gr00t_controller_node import main
if __name__ == '__main__':
    main()
